### ISSUE TITLE
`--check` option

### ISSUE THREAD

**Issue by Szegoo** [paritytech/psvm#10]
I would like to use psvm in my CI workflow to ensure the correct dependency versions are used. It would be good to add a `--check` flag that exits with a non-zero status code if the dependencies need updating.

**Comment by SachinCoder1** [comment]
Hi @Szegoo Can you please tell more about it ? 
like: 
- What is expected by this --check (it is unclear still)
- what do you mean by non zero status code ? a warning ? 
- correct dependency versions ? 

I am interested on working this **issue**...

**Comment by shawntabrizi** [comment]
@SachinCoder1 I think its just having a command that tells the user that some dependencies would be updated, without actually updating them. I think PSVM only goes in and actually makes changes to files.

I am guessing this check flag would return to the user what would change without actually changing it.

I think, based on your questions, you need to familiarize yourself with this tool more.

**Comment by 0xsouravm** [comment]
Please refer to PR #21 for the implementation of this issue. As per @Szegoo, the program exits with an error whenever it finds a dependency that doesn't match to the correct expected version.

Command: psvm --check <VERSION>

(similar to the --version flag usage)

**Comment by Szegoo** [comment]
> @SachinCoder1 I think its just having a command that tells the user that some dependencies would be updated, without actually updating them. I think PSVM only goes in and actually makes changes to files.
> 
> I am guessing this check flag would return to the user what would change without actually changing it.
> 
> I think, based on your questions, you need to familiarize yourself with this tool more.

Great to see a PR, I am reviewing it now.

But yes, this is what I meant when writing the issue. This way we can use `psvm` in a CI workflow to ensure all the dependencies have the correct version. Exiting with an error(non zero status code) would indicate that some dependencies have incorrect versions and the CI check would fail.

**Comment by shawntabrizi** [comment]
closed by https://github.com/paritytech/psvm/pull/21
