### ISSUE TITLE
parser not fully toml compliant

### ISSUE THREAD

**Issue by brenzi** [paritytech/psvm#4]
Tried this in the root folder of https://github.com/integritee-network/parachain

reproduce: `psvm -v "1.9.0"`

what doesn't work:

`cumulus-client-cli = "0.7.0"`
should become
`cumulus-client-cli = "0.10.0"`

but it only works if I do
`cumulus-client-cli = { version = "0.7.0" }`
which then becomes 
`cumulus-client-cli = { version = "0.10.0" }`

**Comment by ggwpez** [comment]
Fixing in #5.
