### ISSUE TITLE
Possible Missed Package jsonrpsee

### ISSUE THREAD

**Issue by JesseAbram** [paritytech/psvm#8]
First of all this is amazing, made updating substrate super easy. However I did have it miss jsonrpsee update. Not sure if there is a reason or was just an oversight

**Comment by ggwpez** [comment]
You mean the `jsonrpsee` is not being updated by this? Yes, `jsonrpsee` is not part of Substrate and should be possible to update at your own pace.  
Did this cause an issue for you?

**Comment by JesseAbram** [comment]
It did but my bad didn't realize it wasn't part of substrate

**Comment by niklasad1** [comment]
> You mean the jsonrpsee is not being updated by this? Yes, jsonrpsee is not part of Substrate and should be possible to update at your own pace.
Did this cause an issue for you?

What do you mean by that? That the crate isn't part of polkadot-sdk and just a dependency that could handled via Cargo.lock?
