### ISSUE TITLE
fetch versions mapping online

### ISSUE THREAD

**Issue by xlc** [paritytech/psvm#9]
I don't want to reinstall psvm for every new polkadot-sdk release. It just doesn't make sense.
It should discover the new release mapping and just works with the new release as soon as it is released.

and wen 1.10.0?

**Comment by patriciobcs** [comment]
Yes! This will be the ideal, I'm working on a solution to get the version directly from a Polkadot SDK branch.

**Comment by ggwpez** [comment]
This would also allow it to stay up to date in case we backport something.

**Comment by patriciobcs** [comment]
@xlc This feature is now working! You update to v0.2.0 and run fo example `cargo psvm -v 1.10.0`.
